### ISSUE TITLE
problem when deploying 

### ISSUE THREAD

**Issue by OriginalPlugin** [killercaillou657/Wrapper-Shop#1]
-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
       
 !     ERROR: Application not supported by 'heroku/nodejs' buildpack
 !     
 !     The 'heroku/nodejs' buildpack is set on this application, but was
 !     unable to detect a Node.js codebase.
 !         
 !     A Node.js app on Heroku requires a 'package.json' at the root of
 !     the directory structure.
 !     
 !     If you are trying to deploy a Node.js application, ensure that this
 !     file is present at the top level directory. This directory has the
 !     following files:
 !     
 !     categories/
 !     favicon.ico
 !     home.html
 !     index.php
 !     LICENSE
 !     pages/
 !     README.md
 !         
 !     If you are trying to deploy an application written in another
 !     language, you need to change the list of buildpacks set on your
 !     Heroku app using the 'heroku buildpacks' command.
 !         
 !     For more information, refer to the following documentation:
 !     https://devcenter.heroku.com/articles/buildpacks
 !     https://devcenter.heroku.com/articles/nodejs-support#activation
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

**Comment by killercaillou657** [comment]
this isn't a node.js website

**Comment by linuxbuilder** [comment]
whats the buildpacks anyway

**Comment by killercaillou657** [comment]
php

**Comment by killercaillou657** [comment]
just use the index.php file i added
